version: '3.9'
services:
  #pizzeria_app:
  #  depends_on:
  #    db:
  #      condition: service_completed_successfully
  db:
    image: 'mysql:8.0'
    container_name: 'pizzeria_db'
    restart: always
    environment:
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_USER=mysql'
      - 'MYSQL_PASSWORD=mysql'
      - 'MYSQL_DATABASE=dotnet_pizzeria'
    ports:
      - '3306:3306'
    volumes:
      - 'dotnet_pizzeria:/var/lib/mysql'
    healthcheck:
      test: "mysql ${MYSQL_DATABASE} \
              --user='${MYSQL_USER}' \
              --password='${MYSQL_PASSWORD}' \
              --silent --execute \"SELECT 1;\""
      interval: 60s
      timeout: 10s
      retries: 5 
volumes:
  dotnet_pizzeria:
